[package]
name = "firefly"
version = "0.1.0"
edition = "2024"

[dependencies]
rodio = "0.21.0"
ratatui = "0.28.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
rfd = "0.15.4"
lofty = "0.22.4"
ez-ffmpeg = "*"
